// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMawcF6lvA39J3mC5fE-cNC7GKwtYWa90',
    appId: '1:213962701257:web:9424f037a3c16961ae1018',
    messagingSenderId: '213962701257',
    projectId: 'smart-hajj-umrah-app',
    authDomain: 'smart-hajj-umrah-app.firebaseapp.com',
    storageBucket: 'smart-hajj-umrah-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1oOe2AvHw6irHsPp6l3DqKDbcttAizI',
    appId: '1:213962701257:android:572f590e835c6b80ae1018',
    messagingSenderId: '213962701257',
    projectId: 'smart-hajj-umrah-app',
    storageBucket: 'smart-hajj-umrah-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVwJV6f3WAoCUTBlRDEYRcmYIwfA5WVM',
    appId: '1:213962701257:ios:9d4540345edc2c40ae1018',
    messagingSenderId: '213962701257',
    projectId: 'smart-hajj-umrah-app',
    storageBucket: 'smart-hajj-umrah-app.firebasestorage.app',
    iosBundleId: 'com.example.hajjApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwVwJV6f3WAoCUTBlRDEYRcmYIwfA5WVM',
    appId: '1:213962701257:ios:9d4540345edc2c40ae1018',
    messagingSenderId: '213962701257',
    projectId: 'smart-hajj-umrah-app',
    storageBucket: 'smart-hajj-umrah-app.firebasestorage.app',
    iosBundleId: 'com.example.hajjApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMawcF6lvA39J3mC5fE-cNC7GKwtYWa90',
    appId: '1:213962701257:web:a2c7c793b94ec3b5ae1018',
    messagingSenderId: '213962701257',
    projectId: 'smart-hajj-umrah-app',
    authDomain: 'smart-hajj-umrah-app.firebaseapp.com',
    storageBucket: 'smart-hajj-umrah-app.firebasestorage.app',
  );
}
